site_name: Causal Validation
repo_url: https://github.com/amazon-science/causal-validation
site_url: https://amazon-science.github.io/causal-validation/
repo_name: causal-validation

nav:
  - Home: index.md
  - Examples:
    - Data Synthesis: examples/basic.ipynb
    - Placebo Testing: examples/placebo_test.ipynb
    - AZCausal Integration: examples/azcausal.ipynb

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - content.code.copy

markdown_extensions:
  - abbr
  - admonition

plugins:
  - search
  - mknotebooks:
      execute: true
      allow_errors: false

extra:
  version:
    provider: mike

watch:
  - src