site_name: Causal Validation
repo_url: https://github.com/amazon-science/causal-validation
site_url: https://amazon-science.github.io/causal-validation/
repo_name: causal-validation

nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
    - Data Synthesis: examples/basic.ipynb
    - Placebo Testing: examples/placebo_test.ipynb
    - AZCausal Integration: examples/azcausal.ipynb

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - content.code.copy
  palette:
    scheme: reds

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      pygments_style: vs
      noclasses: true

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
      timezone: Europe/Amsterdam
      locale: en
      exclude:
        - index.md
        - installation.md
      fallback_to_build_date: false
      enable_creation_date: true
  - mknotebooks:
      execute: true
      allow_errors: false
      binder: true
      binder_service_name: "gh"
      binder_branch: "master"
      binder_ui: "lab"
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src