site_name: Causal Validation
repo_url: https://github.com/amazon-science/causal-validation
site_url: https://amazon-science.github.io/causal-validation/
repo_name: causal-validation

nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
    - Data Synthesis: examples/basic.ipynb
    - Placebo Testing: examples/placebo_test.ipynb
    - AZCausal Integration: examples/azcausal.ipynb

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - content.code.copy
  palette:
    scheme: reds

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
      pygments_style: autumn
      noclasses: true

plugins:
  - search
  - mknotebooks:
      execute: true
      allow_errors: false

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src