name: Build Documentation

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    concurrency: ci-${{ github.ref }}
    name: Build docs
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Grap the latest commit from the branch
      - name: Checkout the branch
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build and deploy the documentation
        run: hatch run docs:deploy

      - name: Deploy Page 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site