name: Test Documentation

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-docs:
    concurrency: ci-${{ github.ref }}
    name: Test docs
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Grap the latest commit from the branch
      - name: Checkout the branch
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build the documentation
        run: hatch run docs:build